# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ak47', '0002_auto_20170324_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='posts'),
        ),
        migrations.AlterField(
            model_name='post',
            name='movie',
            field=models.URLField(blank=True),
        ),
    ]
