# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ak47', '0003_auto_20170324_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(upload_to='user/avatar/'),
        ),
    ]
