# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 18:01
from __future__ import unicode_literals

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ak47', '0004_auto_20170324_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='movie',
            field=embed_video.fields.EmbedVideoField(),
        ),
    ]
