# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 18:20
from __future__ import unicode_literals

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ak47', '0005_auto_20170403_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='movie',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
    ]
