# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ak47', '0007_auto_20170404_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='posts/%id/%title'),
        ),
    ]
