# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-06 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ak47', '0009_auto_20170605_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='like_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
